[package]
name = "OBR"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
memmap2 = "0.9.4"
memchr = "2.7.1"
rayon = "1.9.0"
hashbrown = "0.14.3"